# Generated by Django 4.1.13 on 2026-02-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Setup'), ('PE', 'Pending'), ('P', 'Processing'), ('C', 'Completed')], default='S', max_length=20)),
                ('type', models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('AUD', 'Audio')], max_length=20)),
                ('target_fmt', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('use', models.CharField(choices=[('C', 'Conversion'), ('R', 'Result')], default='C', max_length=20)),
                ('type', models.CharField(max_length=100)),
                ('size', models.IntegerField(null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.convertrequest')),
            ],
        ),
    ]
