# Generated by Django 3.2.9 on 2021-11-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertrequest',
            name='status',
            field=models.CharField(default='not-started', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='use',
            field=models.CharField(default='conversion', max_length=20),
        ),
        migrations.AlterField(
            model_name='convertrequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
