# Generated by Django 3.2.9 on 2021-11-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211107_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertrequest',
            name='status',
            field=models.CharField(choices=[('S', 'Setup'), ('PE', 'Pending'), ('P', 'Processing'), ('C', 'Completed')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='use',
            field=models.CharField(choices=[('C', 'Conversion'), ('R', 'Result')], default='C', max_length=20),
        ),
    ]
