# Generated by Django 3.2.9 on 2021-11-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211107_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertrequest',
            name='convert_to',
            field=models.CharField(default='11', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convertrequest',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video')], default='11', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='11', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video')], default='11', max_length=20),
            preserve_default=False,
        ),
    ]
