# Generated by Django 3.2.9 on 2021-11-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211107_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
