# Generated by Django 3.2.9 on 2021-11-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_file_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertrequest',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('AUD', 'Audio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('AUD', 'Audio')], max_length=20),
        ),
    ]
