# Generated by Django 4.1.5 on 2023-01-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_file_file_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='type',
            new_name='content_type',
        ),
    ]
